# Available images: 
# $ gcloud container images list --repository="gcr.io/deeplearning-platform-release"
FROM gcr.io/sabeti-encode/boda/base:0.1.2

WORKDIR /

ENTRYPOINT ["python", "/opt/ml/code/main.py"]
